// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQc-Az_dux290KMU8uKARo_YzN4u8Uv8',
    appId: '1:860666419301:web:6e6cd24735ebf4e36f8e8c',
    messagingSenderId: '860666419301',
    projectId: 'fir-flutter-demo-11d1c',
    authDomain: 'fir-flutter-demo-11d1c.firebaseapp.com',
    storageBucket: 'fir-flutter-demo-11d1c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRzxthjKPFPy2We_kXQfiSEBqyw2PTMI0',
    appId: '1:860666419301:ios:975a22ed7f01a3586f8e8c',
    messagingSenderId: '860666419301',
    projectId: 'fir-flutter-demo-11d1c',
    storageBucket: 'fir-flutter-demo-11d1c.appspot.com',
    iosClientId: '860666419301-tnl5f8qcbjnt69fvagojbf3olf1gil19.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuthAttempt.RunnerTests',
  );
}
